version: '3'

  services:
    app:
      container_name: academy
      build: .
      ports:
        - '80:3000'
      links:
        - mongo
        - redis
    
    mongo:
      container_name: mongo
      environment:
        MONGODB_DATABASE: "academy"
      volumes:
        - /var/lib/docker/volumes/data/_data:/data/db
      image: mongo
    
    redis:
      image: redis
      ports:
        - "6379"